export const CHANGE_NUMBER = 'CHANGE_NUMBER';
export const SET_USER_VALUE = 'SET_USER_VALUE';
export const SET_FORM_TILE = 'SET_FORM_TILE'
export const SET_FORM_VALUE ='SET_FORM_VALUE'
export const ADD_TASK = 'ADD_TASK'
export const EDIT_ITEM = 'EDIT_ITEM'
export const EDIT_CANCEL = 'EDIT_CANCEL'
export const DELETE_ITEM = 'DELETE_ITEM'
export const SET_FILTER = 'SET_FILTER'

export default {
  CHANGE_NUMBER,
  SET_USER_VALUE,
  SET_FORM_TILE,
  SET_FORM_VALUE,
  ADD_TASK,
  EDIT_ITEM,
  EDIT_CANCEL,
  DELETE_ITEM,
  SET_FILTER
};
